### ISSUE TITLE
fail2ban

### ISSUE THREAD

**Issue by blittle** [coolaj86/iojs-install-script#1]
Why is this installing fail2ban?

**Comment by coolaj86** [comment]
It wouldn't if you had already installed it. :-)

Because, as describe in README and the screencast, I estimate that the kind of people that are using this install script are probably more towards the novice end of the spectrum and I don't want their VPSes to turn into botnets.

**Comment by blittle** [comment]
I am not debating the whether fail2ban should be on the server or not, more that it seems odd that an install script for io.js would have a totally unrelated side effect of installing fail2ban.

**Comment by coolaj86** [comment]
This is the script I link to in my tutorials and blog posts for new developers.

It also installs wget, curl, rsync, gcc. Those, however, are used by the script or npm during install.

I suppose I could remove it and just print something at the bottom like:

> fail2ban is missing from you system. This isn't necessary for iojs,
> but since iojs is most often used on network-connected system
> you should install it before continuing with any further development
> - we don't want your server being reaped by a botnet, y'know :-)

**Comment by blittle** [comment]
just very non-unixy...shouldn't you have a "setup-development-environment" script that does all of that instead of the "iojs-install-script"?

**Comment by coolaj86** [comment]
I've made several changes to the installer scripts:
- doesn't automatically install fail2ban
- doesn't stomp the existing version of node
- does clearly inform the user what's being checked for (and installed)

**Comment by coolaj86** [comment]
I'm gonna close this now, but I'm open for further discussion. I also added bit.ly/iojs-min that won't install git, rsync, xcode, etc either.
