### ISSUE TITLE
bc is not installed on all systems

### ISSUE THREAD

**Issue by strebl** [coolaj86/iojs-install-script#7]
If I run your script on a Raspbian installation, it fails because bc isn't installed.

**Comment by coolaj86** [comment]
Originally I was trying to match the major and minor version, but I think I could just match the major and use a bash comparison operator instead of bc.

**Comment by strebl** [comment]
Yeah, I thinks that would be a good solution.
I think it's not worth to install bc because of that.

**Comment by strebl** [comment]
Do you have any idea when you have time to work on this issue?

**Comment by coolaj86** [comment]
Hey, I think I fixed this recently. Sorry for not responding.
